"""Build the ScanCrypt verification corpus.

Materialises a set of sample images that reproduce the encryption patterns ScanCrypt is
built to measure, so anyone can check the tool's claims on their own machine without needing
a real ransomware sample or a victim's data.

The samples contain NO real data and NO real ransomware output:

  - The "encrypted" regions are uniform random bytes from a seeded generator. That is what a
    block cipher in a streaming mode looks like statistically, which is all the entropy and
    chi-square analysis ever sees. Nothing here is produced by, or derived from, a malware
    binary.
  - The "intact" regions are synthetic record-structured text, standing in for the kind of
    low-entropy content that fills a real database or document store.

Everything is seeded, so two people running this get byte-identical files and the same
SHA-256 in manifest.json. Run with --verify to re-check an existing corpus.

    python samples/make_samples.py            # build into samples/corpus/
    python samples/make_samples.py --verify   # re-hash and compare against the manifest

Sizes are kept modest (256 MiB total) so this is a two-minute exercise rather than an
afternoon. The patterns, not the sizes, are what the tool reads.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import sys
import zlib

MIB = 1024 * 1024
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "corpus")

# One fixed seed for the whole corpus keeps the build reproducible; each sample derives its
# own stream from it so adding a sample never changes the bytes of the existing ones.
MASTER_SEED = 20260803


def _record_text(rng: random.Random, n: int) -> bytes:
    """Synthetic record-structured content: what the *recoverable* part of a real file looks
    like. Deliberately low-entropy and repetitive, the way real database pages and documents
    are -- if this were random, there would be nothing for the tool to distinguish."""
    first = ["Sandra", "Peter", "Amara", "Wei", "Tomas", "Priya", "Liam", "Ngozi", "Hana"]
    last = ["Whitfield", "Nguyen", "Okafor", "Silva", "Kowalski", "Tanaka", "Murphy", "Haddad"]
    city = ["Townsville", "Brisbane", "Perth", "Adelaide", "Hobart", "Darwin", "Geelong"]
    out = bytearray()
    i = 0
    while len(out) < n:
        i += 1
        row = (f"REC{i:09d}|{rng.choice(first)} {rng.choice(last)}|"
               f"{rng.choice(city)}|{rng.randrange(1000, 9999)}|"
               f"{rng.randrange(10 ** 9, 10 ** 10)}|ACTIVE|\n")
        out += row.encode("ascii")
    return bytes(out[:n])


def _cipherlike(rng: random.Random, n: int) -> bytes:
    """Uniform random bytes -- statistically indistinguishable from block-cipher output, and
    the only property the analysis depends on. Not generated by any malware."""
    return rng.randbytes(n)


def _deflate(rng: random.Random, n: int) -> bytes:
    """Real DEFLATE output (the algorithm behind ZIP/OOXML/PNG/gzip), which reads ~8 bits per
    byte just like encryption. This is the case entropy alone gets wrong."""
    out = bytearray()
    while len(out) < n:
        out += zlib.compress(_record_text(rng, 512 * 1024), 9)
    return bytes(out[:n])


def build_front_only_large(path: str) -> dict:
    """The headline pattern: a large file with only its front encrypted. This is the shape of
    the real incident that prompted the tool -- a 101 GB SQL Server disk with roughly 1 MB
    actually encrypted."""
    rng = random.Random(MASTER_SEED + 1)
    total, enc = 128 * MIB, 1 * MIB
    with open(path, "wb") as fh:
        fh.write(_cipherlike(rng, enc))
        remaining = total - enc
        while remaining > 0:
            chunk = min(8 * MIB, remaining)
            fh.write(_record_text(rng, chunk))
            remaining -= chunk
    return {"bytes": total, "encrypted_bytes": enc,
            "pattern": "front-only",
            "note": "Large file, small encrypted front. The core case."}


def build_front_only_narrow(path: str) -> dict:
    """The same pattern at the boundary width actually measured in the incident: 200,704
    bytes. A coarse fixed-interval scan can miss a region this narrow entirely and write the
    file off as lost -- which is the failure mode the tool exists to prevent."""
    rng = random.Random(MASTER_SEED + 2)
    total, enc = 32 * MIB, 200_704
    with open(path, "wb") as fh:
        fh.write(_cipherlike(rng, enc))
        remaining = total - enc
        while remaining > 0:
            chunk = min(8 * MIB, remaining)
            fh.write(_record_text(rng, chunk))
            remaining -= chunk
    return {"bytes": total, "encrypted_bytes": enc,
            "pattern": "front-only",
            "note": "Boundary at 200,704 bytes, the width measured in the real incident."}


def build_periodic(path: str) -> dict:
    """Intermittent/striped encryption: the newer approach, where a crew encrypts a slice at
    a fixed stride through the file rather than just the front. Harder to recover from, and
    it needs a full block scan rather than a boundary search."""
    rng = random.Random(MASTER_SEED + 3)
    total, stride, slice_len = 64 * MIB, 8 * MIB, 512 * 1024
    written = 0
    with open(path, "wb") as fh:
        while written < total:
            block = min(stride, total - written)
            enc = min(slice_len, block)
            fh.write(_cipherlike(rng, enc))
            if block > enc:
                fh.write(_record_text(rng, block - enc))
            written += block
    return {"bytes": total, "encrypted_bytes": (total // stride) * slice_len,
            "pattern": "periodic-intermittent",
            "note": f"{slice_len // 1024} KiB encrypted every {stride // MIB} MiB."}


def build_compressed_benign(path: str) -> dict:
    """Not encrypted at all -- real DEFLATE output. Entropy alone reads this at ~8 bits per
    byte and calls it ciphertext, which would write off a perfectly intact archive as lost.
    ScanCrypt should report it as benign compressed content."""
    rng = random.Random(MASTER_SEED + 4)
    total = 32 * MIB
    with open(path, "wb") as fh:
        remaining = total
        while remaining > 0:
            chunk = min(8 * MIB, remaining)
            fh.write(_deflate(rng, chunk))
            remaining -= chunk
    return {"bytes": total, "encrypted_bytes": 0,
            "pattern": "compressed-benign",
            "note": "No encryption. High entropy, but structurally compressed, not random."}


SAMPLES = [
    ("01-front-only-large.img", build_front_only_large),
    ("02-front-only-narrow-boundary.img", build_front_only_narrow),
    ("03-periodic-intermittent.img", build_periodic),
    ("04-compressed-benign.img", build_compressed_benign),
]


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(4 * MIB), b""):
            h.update(block)
    return h.hexdigest()


def build() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    manifest = {"seed": MASTER_SEED, "samples": {}}
    for name, fn in SAMPLES:
        path = os.path.join(OUT_DIR, name)
        print(f"building {name} ...", end=" ", flush=True)
        meta = fn(path)
        meta["sha256"] = sha256(path)
        manifest["samples"][name] = meta
        print(f"{meta['bytes'] // MIB} MiB  sha256={meta['sha256'][:16]}...")
    with open(os.path.join(OUT_DIR, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")
    print(f"\n{len(SAMPLES)} samples written to {OUT_DIR}")
    print("manifest.json holds the SHA-256 of each; rerun with --verify to re-check.")
    return 0


def verify() -> int:
    mpath = os.path.join(OUT_DIR, "manifest.json")
    if not os.path.exists(mpath):
        print("no manifest.json -- build the corpus first", file=sys.stderr)
        return 2
    with open(mpath, encoding="utf-8") as fh:
        manifest = json.load(fh)
    bad = 0
    for name, meta in manifest["samples"].items():
        path = os.path.join(OUT_DIR, name)
        if not os.path.exists(path):
            print(f"MISSING  {name}")
            bad += 1
            continue
        actual = sha256(path)
        ok = actual == meta["sha256"]
        print(f"{'ok      ' if ok else 'MISMATCH'} {name}")
        bad += not ok
    print("\nall samples match the manifest" if not bad else f"\n{bad} problem(s)")
    return 1 if bad else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build the ScanCrypt verification corpus.")
    ap.add_argument("--verify", action="store_true",
                    help="re-hash an existing corpus and compare against manifest.json")
    args = ap.parse_args(argv)
    return verify() if args.verify else build()


if __name__ == "__main__":
    raise SystemExit(main())
